default_platform(:ios)

platform :ios do

  before_all do
      
    setup_ci

  end

  desc "Submit a new Beta apk for testing"
  lane :beta do

    api_key = app_store_connect_api_key(
      key_id: ENV['APPLE_KEY_ID'],
      issuer_id: ENV['APPLE_KEY_ISSUER_ID'],
      key_content: ENV['APPLE_KEY_CONTENT'],
    )

    use_workspace = !ENV['IOS_WORKSPACE_PATH'].empty?

    match(
      readonly: true,
      git_basic_authorization: Base64.strict_encode64(ENV['MATCH_GIT_TOKEN']),
      api_key: api_key
    )

    build_app(
      workspace: use_workspace ? ENV['IOS_WORKSPACE_PATH'] : nil,
      scheme: "agogochop",
      silent: true,
      output_directory: File.dirname(ENV['IOS_OUTPUT_PATH']),
      output_name: File.basename(ENV['IOS_OUTPUT_PATH']),
      clean: true,
      export_method: "app-store",
      export_team_id: ENV['APPLE_TEAM_ID'],
      export_options: {
        provisioningProfiles: {
          "com.agogochop.marketplace" => "match AppStore com.agogochop.marketplace",
        },
      }
    )

    upload_to_testflight(
      ipa: File.join(File.dirname(ENV['IOS_OUTPUT_PATH']), File.basename(ENV['IOS_OUTPUT_PATH'])),
      api_key: api_key,
      changelog: "Happy Testing !!!😄",
      groups: ENV['IOS_TEST_GROUPS'],
      distribute_external: true,
    )

  end
end
