default_platform(:android)

platform :android do

  desc "Submit a new Beta apk for testing"
  lane :beta do

    gradle(task: "clean app:assembleRelease")

    firebase_app_distribution(
      app: ENV['ANDROID_APP_ID'],
      groups: ENV['ANDROID_TEST_GROUPS'],
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      release_notes: "Happy Testing !!!😄",
    )

  end

end